const lesson2 = {
  id: "fr-beg-2",
  title: "Francuski — Poziom 2 (początkujący)",
  level: "Początkujący",
  description:
    "Rozszerzamy fundamenty: c’est / il est, il y a, ‘combien’, posiadanie (mon/ma/mes), liczba mnoga, negacja z ‘de’, wiek z ‘avoir’.",
  theorySections: [
    { title: "C’est vs Il est", html: `<div class=\"text-sm\">Użyj <em>C'est</em> przed rzeczownikiem (<em>C'est mon frère.</em>). <em>Il est</em> zwykle przed przymiotnikiem (<em>Il est fatigué.</em>).</div>` },
    { title: "Il y a", html: `<div class=\"text-sm\"><em>Il y a</em> wyraża istnienie: <em>Il y a de l'eau dans le frigo.</em></div>` },
    { title: "Negacja z de", html: `<div class=\"text-sm\">Po negacji często <em>de</em> zamiast rodzajnika: <em>Je n'ai pas de czas</em>.</div>` },
    { title: "Wiek z avoir", html: `<div class=\"text-sm\">Po francusku „mieć” lata: <em>J'ai vingt-cinq ans.</em></div>` },
    { title: "Zaimki dzierżawcze", html: `<div class=\"text-sm\">Zależne od rzeczownika: <em>mon frère</em>, <em>ma sœur</em>, <em>mes amis</em>.</div>` },
    { title: "Demonstratywne", html: `<div class=\"text-sm\"><em>ce/cet/cette/ces</em>: <em>ces élèves</em> (ci uczniowie).</div>` },
    { title: "Pytanie: combien", html: `<div class=\"text-sm\"><em>Combien ça coûte ?</em> / <em>Ça coûte combien ?</em></div>` },
  ],
  tasks: [
    { id: 1, direction: "PL → FR", prompt: "Mam na imię Anna.", answers: ["je mappelle anna", "je m appelle anna"], note: "<em>S'appeler</em>: <em>je m'appelle</em> (m')." },
    { id: 2, direction: "PL → FR", prompt: "Ile to kosztuje?", answers: ["combien ca coute", "ca coute combien"], note: "Dwa warianty pytania." },
    { id: 3, direction: "PL → FR", prompt: "Mamy dwa psy.", answers: ["nous avons deux chiens", "on a deux chiens"], note: "Mnoga: <em>deux chiens</em>." },
    { id: 4, direction: "PL → FR", prompt: "To jest mój brat.", answers: ["cest mon frere"], note: "<em>C'est</em> + rzeczownik; <em>mon</em> + męski «frère»." },
    { id: 5, direction: "PL → FR", prompt: "Nie mam czasu.", answers: ["je nai pas le temps", "je nai pas de temps", "je n ai pas le temps"], note: "Negacja <em>ne… pas</em>; idiom: <em>le temps</em>." },
    { id: 6, direction: "PL → FR", prompt: "W lodówce jest woda.", answers: ["il y a de leau dans le frigo"], note: "<em>Il y a</em> + partitif <em>de l'eau</em>." },
    { id: 7, direction: "PL → FR", prompt: "Ci uczniowie są zmęczeni.", answers: ["ces eleves sont fatigues"], note: "<em>ces élèves</em>, przym. mnoga: <em>fatigués</em>." },
    { id: 8, direction: "PL → FR", prompt: "Mam 25 lat.", answers: ["jai vingt cinq ans"], note: "Wiek z <em>avoir</em>: <em>j'ai … ans</em>." },
    { id: 9, direction: "PL → FR", prompt: "Gdzie są klucze?", answers: ["ou sont les cles"], note: "<em>Où</em> = gdzie. Mnoga: <em>les clés</em>." },
    { id: 10, direction: "PL → FR", prompt: "Proszę powtórzyć, proszę.", answers: ["repetez sil vous plait", "pouvez vous repeter sil vous plait"], note: "<em>Répétez, s'il vous plaît.</em> / <em>Pouvez‑vous répéter… ?</em>" },
  ],
  vocab: [
    { fr: "combien", pl: "ile", pos: "przysł.", ipa: "kɔ̃bjɛ̃" },
    { fr: "coûter", pl: "kosztować", pos: "czas.", ipa: "kute" },
    { fr: "deux", pl: "dwa", pos: "licz.", ipa: "dø" },
    { fr: "chien / chiens", pl: "pies / psy", pos: "rzecz.", gender: "m", ipa: "ʃjɛ̃" },
    { fr: "c'est", pl: "to jest", pos: "zwrot", ipa: "sɛ" },
    { fr: "mon / ma / mes", pl: "mój / moja / moi/moje", pos: "det.", ipa: "mɔ̃ / ma / me" },
    { fr: "frère", pl: "brat", pos: "rzecz.", gender: "m", ipa: "fʁɛʁ" },
    { fr: "ne … pas", pl: "nie (negacja)", pos: "konstrukcja", ipa: "nə … pa" },
    { fr: "temps", pl: "czas", pos: "rzecz.", gender: "m", ipa: "tɑ̃" },
    { fr: "il y a", pl: "jest/są (znajduje się)", pos: "zwrot", ipa: "il ja" },
    { fr: "dans", pl: "w", pos: "przyim.", ipa: "dɑ̃" },
    { fr: "frigo", pl: "lodówka", pos: "rzecz.", gender: "m", ipa: "fʁigo" },
    { fr: "ces", pl: "ci/te", pos: "det.", ipa: "se" },
    { fr: "élève(s)", pl: "uczeń/uczniowie", pos: "rzecz.", gender: "m/f", ipa: "elɛv" },
    { fr: "fatigué(e)(s)", pl: "zmęczony/a/i/e", pos: "przym.", ipa: "fatiɡe" },
    { fr: "j'ai … ans", pl: "mam … lat", pos: "zwrot", ipa: "ʒe ɑ̃" },
    { fr: "vingt-cinq", pl: "dwadzieścia pięć", pos: "licz.", ipa: "vɛ̃ sɛ̃k" },
    { fr: "clé(s)", pl: "klucz(e)", pos: "rzecz.", gender: "f", ipa: "kle" },
    { fr: "répéter", pl: "powtarzać", pos: "czas.", ipa: "ʁepete" },
    { fr: "pouvez-vous", pl: "czy może Pan/Pani", pos: "zwrot", ipa: "puve vu" },
  ],
};

export default lesson2;